import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

// google font
import {Outfit} from 'next/font/google'
const outfit=Outfit({subsets:['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={outfit.className} // google font applied
        >
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
    
  );
}
